import type { Metadata } from "next";
 
import { CartProvider } from "./context/CartContext";
import Navbar from "../component/Navbar";
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-white">
          <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
          <CartProvider >
            <Navbar />
            {children}
          </CartProvider>
      </body>
    </html>
  );
}
